# Generated by Django 5.0.6 on 2026-07-03 02:46

import apps.deliveries.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=apps.deliveries.models.generate_tracking_code, editable=False, max_length=20, unique=True, verbose_name='código de seguimiento')),
                ('client_name', models.CharField(max_length=120, verbose_name='cliente')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='peso (kg)')),
                ('origin_address', models.CharField(max_length=255, verbose_name='origen')),
                ('origin_lat', models.FloatField(verbose_name='latitud origen')),
                ('origin_lng', models.FloatField(verbose_name='longitud origen')),
                ('destination_address', models.CharField(max_length=255, verbose_name='destino')),
                ('destination_lat', models.FloatField(verbose_name='latitud destino')),
                ('destination_lng', models.FloatField(verbose_name='longitud destino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'paquete',
                'verbose_name_plural': 'paquetes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_TRANSIT', 'En tránsito'), ('DELIVERED', 'Entregado')], default='PENDING', max_length=12, verbose_name='estado')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='programada')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='conductor')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='vehicles.vehicle', verbose_name='vehículo')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='deliveries.package', verbose_name='paquete')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-created_at'],
            },
        ),
    ]
