# Generated by Django 5.0.6 on 2026-07-26 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_label', models.CharField(max_length=120, verbose_name='etiqueta de origen')),
                ('origin_lat', models.FloatField(verbose_name='latitud de origen')),
                ('origin_lng', models.FloatField(verbose_name='longitud de origen')),
                ('total_distance_km', models.FloatField(verbose_name='distancia total (km)')),
                ('estimated_time_min', models.FloatField(verbose_name='tiempo estimado (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_created', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='conductor')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='vehicles.vehicle', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('distance_from_prev_km', models.FloatField(verbose_name='distancia desde la anterior (km)')),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_stop', to='deliveries.delivery', verbose_name='entrega')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route', verbose_name='ruta')),
            ],
            options={
                'verbose_name': 'parada',
                'verbose_name_plural': 'paradas',
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
