# Generated by Django 5.0.6 on 2026-07-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='geometry',
            field=models.JSONField(blank=True, null=True, verbose_name='geometría de la ruta'),
        ),
        migrations.AddField(
            model_name='route',
            name='routing_source',
            field=models.CharField(choices=[('OSRM', 'Calles reales (OSRM)'), ('HAVERSINE', 'Línea recta (estimación)')], default='HAVERSINE', max_length=10, verbose_name='fuente de ruteo'),
        ),
    ]
