# Generated by Django 5.0.6 on 2026-07-03 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=15, unique=True, verbose_name='placa')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='modelo')),
                ('vehicle_type', models.CharField(choices=[('VAN', 'Furgoneta'), ('TRUCK', 'Camión'), ('MOTORCYCLE', 'Motocicleta')], default='VAN', max_length=12, verbose_name='tipo')),
                ('capacity_kg', models.PositiveIntegerField(default=0, verbose_name='capacidad (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='conductor')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['plate'],
            },
        ),
    ]
